plugin: aws_ec2
regions:
  - eu-west-3
filters:
  instance-state-name: running
  "tag:Name": "pokito-*" # Ne récupère que les machines de notre projet

hostnames:
  # - tag:Name
  - instance-id

# Classe les machines dans des groupes Ansible basés sur le Tag "Role"
keyed_groups:
  - key: tags.Role
    prefix: role

# Indique à Ansible de ne pas utiliser SSH, mais le tunnel AWS SSM
compose:
  ansible_connection: "'aws_ssm'"
  ansible_aws_ssm_region: "'eu-west-3'"
  ansible_aws_ssm_bucket_name: "'pokito-tf-state-lasreex-250832562692-eu-west-3-an'"
  # Utilise l'ID de l'instance (i-0abcd...) comme cible de connexion au lieu de l'IP
  #ansible_host: instance_id