name: Build et Push de l'image Docker

on:
  push:
    branches:
      - main # Le déclencheur : un push sur main
    paths:
      - 'website/**'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # On donne les droits au script d'écrire dans le registre d'images GitHub
    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Connexion au registre GitHub (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build et Push de l'image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Attention : le nom de l'image doit TOUJOURS être en minuscules dans Docker
          tags: ghcr.io/lasreex/bloc5_pokito:latest