name: 1 - Build et Push de l'image Docker

on:
  push:
    branches:
      - main
    # paths:
    #   - 'website/**'
    #   - 'Dockerfile'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Connexion au registre GitHub (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build et Push de l'image (Versionné)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # On génère deux tags d'un coup grâce au '|' (multiligne) : latest ET v{numero_du_pipeline}
          tags: |
            ghcr.io/lasreex/bloc5_pokito:latest
            ghcr.io/lasreex/bloc5_pokito:v${{ github.run_number }}